POST localhost:3000/auth/register HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
	"name": "mmarconm",
	"email": "marcelo5@bol.com",
	"password": "adminadmin"
}

###
POST localhost:3000/auth/authenticate HTTP/1.1
Content-Type: application/json
Host: localhost:3000

{
	"email": "marcelo4@bol.com",
	"password": "adminadmin"
}

### 
GET localhost:3000/projects HTTP/1.1
Content-Type: application/json
Host: localhost:3000
